import uuid
from typing import Literal

from pydantic import BaseModel

# --- AI Agent Output Schemas ---


class ComparableListing(BaseModel):
    """
    Data structure for a single 'comp' (competitor listing) found on a marketplace.
    This is used by Agent 2 to justify its pricing recommendations.
    """

    title: str
    price: float
    currency: str
    condition: str
    item_id: str  # The ID on the external platform (e.g., eBay ID)
    listing_url: str
    # 'validated' means the LLM confirmed this is a match;
    # 'unfiltered' is used if the model skips the validation step.
    relevance: str = "validated"
    similarity_score: float | None = None


class PricingResult(BaseModel):
    """
    The final 'Price Pack' generated by the AI Pricing Agent (Agent 2).
    """

    item_id: uuid.UUID
    recommended_price: float
    confidence_score: float  # AI's certainty in the price (0.0 to 1.0)
    min_acceptable_price: float
    # CI = Confidence Interval (helps show a price range to the seller)
    price_low: float = 0.0
    price_high: float = 0.0
    comparables: list[ComparableListing] = []
    price_std_dev: float = 0.0
    negotiating_posture: str = "THE_CAUTIOUS_MOVE"


class ListingResult(BaseModel):
    """
    The result of an attempt to publish an item to a marketplace.
    This connects the internal Item to the real-world external Listing.
    """

    item_id: uuid.UUID
    platform: Literal["ebay"]  # Restricts values to only "ebay" for now
    status: str  # e.g., "success", "failed", "pending_verification"
    external_id: str | None = None  # The ID assigned by eBay upon successful listing
    listing_url: str | None = None


class CommsResult(BaseModel):
    """
    The output of the Communication Agent when analyzing a buyer's message.
    Used to suggest or automate replies to potential customers.
    """

    message_id: uuid.UUID
    draft_reply: str  # The text the AI thinks we should send
    # action determines if the app should just save the draft, send it immediately,
    # or archive the message as spam/irrelevant.
    action: Literal["draft", "send", "ignore"]
    requires_approval: bool  # If True, the human seller MUST click 'send' manually

    # Negotiation context (populated when the agent handles an offer)
    negotiation_id: uuid.UUID | None = None
    offer_amount: float | None = None

    # NLP analysis summary (for UI display / auditing)
    nlp_intent: str | None = None
    nlp_sentiment: str | None = None
