"""add_pricing_to_items

Revision ID: 4705c798e249
Revises: 0002
Create Date: 2026-04-28 03:40:54.856686

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4705c798e249"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("recommended_price", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        "items", sa.Column("min_acceptable_price", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        "items", sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=True)
    )
    op.add_column("items", sa.Column("price_low", sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column(
        "items", sa.Column("price_high", sa.Numeric(precision=12, scale=2), nullable=True)
    )
    op.add_column(
        "items",
        sa.Column("pricing_comparables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "pricing_comparables")
    op.drop_column("items", "price_high")
    op.drop_column("items", "price_low")
    op.drop_column("items", "confidence_score")
    op.drop_column("items", "min_acceptable_price")
    op.drop_column("items", "recommended_price")
    # ### end Alembic commands ###
