"""add ebay oauth state table

Revision ID: 4d68cffa046a
Revises: a1b2c3d4e5f6
Create Date: 2026-05-08 04:40:56.308107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d68cffa046a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state')
    )
    op.drop_index(op.f('ix_nlp_annotations_message_id'), table_name='nlp_annotations')
    op.drop_table('nlp_annotations')
    op.drop_constraint(op.f('uq_conversations_seller_buyer'), 'conversations', type_='unique')
    op.drop_index(op.f('ix_platform_credentials_external_user_id'), table_name='platform_credentials')
    op.drop_column('platform_credentials', 'external_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_credentials', sa.Column('external_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_platform_credentials_external_user_id'), 'platform_credentials', ['external_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_conversations_seller_buyer'), 'conversations', ['seller_id', 'buyer_handle'], postgresql_nulls_not_distinct=False)
    op.create_table('nlp_annotations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('intent', postgresql.ENUM('offer', 'question', 'status_check', 'spam', 'other', name='intent_label'), autoincrement=False, nullable=False),
    sa.Column('intent_confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('sentiment', postgresql.ENUM('positive', 'neutral', 'negative', name='sentiment_label'), autoincrement=False, nullable=False),
    sa.Column('sentiment_confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('extracted_offer_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['buyer_messages.id'], name=op.f('nlp_annotations_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nlp_annotations_pkey'))
    )
    op.create_index(op.f('ix_nlp_annotations_message_id'), 'nlp_annotations', ['message_id'], unique=True)
    op.drop_table('ebay_oauth_states')
    # ### end Alembic commands ###
