"""unique constraint on conversations seller buyer

Revision ID: 9741be610216
Revises: d4bdb280cde6
Create Date: 2026-05-07 11:29:56.468741

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9741be610216"
down_revision: str | None = "d4bdb280cde6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_conversations_seller_buyer", "conversations", ["seller_id", "buyer_handle"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_conversations_seller_buyer", "conversations", type_="unique")
    # ### end Alembic commands ###
