"""add nlp_annotations and external_user_id

Revision ID: d4bdb280cde6
Revises: dd06bb949617
Create Date: 2026-05-07 10:23:05.255478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4bdb280cde6"
down_revision: str | None = "dd06bb949617"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nlp_annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum("offer", "question", "status_check", "spam", "other", name="intent_label"),
            nullable=False,
        ),
        sa.Column("intent_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum("positive", "neutral", "negative", name="sentiment_label"),
            nullable=False,
        ),
        sa.Column("sentiment_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("extracted_offer_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("entities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["message_id"], ["buyer_messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nlp_annotations_message_id"), "nlp_annotations", ["message_id"], unique=True
    )
    op.add_column(
        "platform_credentials", sa.Column("external_user_id", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_platform_credentials_external_user_id"),
        "platform_credentials",
        ["external_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_platform_credentials_external_user_id"), table_name="platform_credentials"
    )
    op.drop_column("platform_credentials", "external_user_id")
    op.drop_index(op.f("ix_nlp_annotations_message_id"), table_name="nlp_annotations")
    op.drop_table("nlp_annotations")
    sa.Enum(name="sentiment_label").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="intent_label").drop(op.get_bind(), checkfirst=True)
