"""add draft fields to buyer_messages

Revision ID: e12cea1746b1
Revises: 3c337d1046f0
Create Date: 2026-05-14 03:29:44.916785

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e12cea1746b1"
down_revision: str | None = "3c337d1046f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("buyer_messages", sa.Column("draft_reply", sa.Text(), nullable=True))
    op.add_column("buyer_messages", sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buyer_messages", "requires_approval")
    op.drop_column("buyer_messages", "draft_reply")
    # ### end Alembic commands ###
