"""add phase4 tables negotiations sales nlp

Revision ID: f72fb79a80a2
Revises: 4d68cffa046a
Create Date: 2026-05-10 18:37:41.332100

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f72fb79a80a2"
down_revision: str | None = "4d68cffa046a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "negotiations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=True),
        sa.Column("current_offer", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("counter_offer", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("walk_away_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "countered",
                "accepted",
                "declined",
                "expired",
                "seller_review",
                name="negotiation_status",
            ),
            nullable=False,
        ),
        sa.Column("rounds_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_negotiations_conversation_id"), "negotiations", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_negotiations_listing_id"), "negotiations", ["listing_id"], unique=False
    )
    op.create_index(op.f("ix_negotiations_seller_id"), "negotiations", ["seller_id"], unique=False)
    op.create_table(
        "clarification_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("buyer_message_id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["buyer_message_id"], ["buyer_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clarification_requests_buyer_message_id"),
        "clarification_requests",
        ["buyer_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clarification_requests_conversation_id"),
        "clarification_requests",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clarification_requests_seller_id"),
        "clarification_requests",
        ["seller_id"],
        unique=False,
    )
    op.create_table(
        "entity_mentions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("buyer_message_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_value", sa.String(length=255), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=False),
        sa.Column("end_char", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["buyer_message_id"], ["buyer_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entity_mentions_buyer_message_id"),
        "entity_mentions",
        ["buyer_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_mentions_seller_id"), "entity_mentions", ["seller_id"], unique=False
    )
    op.create_table(
        "offer_signals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("buyer_message_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["buyer_message_id"], ["buyer_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_offer_signals_buyer_message_id"),
        "offer_signals",
        ["buyer_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_offer_signals_seller_id"), "offer_signals", ["seller_id"], unique=False
    )
    op.create_table(
        "sales",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("seller_id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=True),
        sa.Column("negotiation_id", sa.UUID(), nullable=True),
        sa.Column("sale_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("buyer_handle", sa.String(length=255), nullable=False),
        sa.Column(
            "platform", postgresql.ENUM("ebay", name="platform", create_type=False), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["negotiation_id"], ["negotiations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["seller_id"], ["sellers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_item_id"), "sales", ["item_id"], unique=False)
    op.create_index(op.f("ix_sales_listing_id"), "sales", ["listing_id"], unique=False)
    op.create_index(op.f("ix_sales_negotiation_id"), "sales", ["negotiation_id"], unique=False)
    op.create_index(op.f("ix_sales_seller_id"), "sales", ["seller_id"], unique=False)
    op.add_column("buyer_messages", sa.Column("seller_id", sa.UUID(), nullable=False))
    op.add_column(
        "buyer_messages", sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_buyer_messages_seller_id"), "buyer_messages", ["seller_id"], unique=False
    )
    op.create_foreign_key(
        None, "buyer_messages", "sellers", ["seller_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("uq_conversations_seller_buyer"), "conversations", type_="unique")
    op.add_column("nlp_annotations", sa.Column("buyer_message_id", sa.UUID(), nullable=False))
    op.add_column("nlp_annotations", sa.Column("seller_id", sa.UUID(), nullable=False))
    op.add_column("nlp_annotations", sa.Column("sentiment_score", sa.Float(), nullable=False))
    op.add_column(
        "nlp_annotations",
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "nlp_annotations",
        "intent",
        existing_type=postgresql.ENUM(
            "offer", "question", "status_check", "spam", "other", name="intent_label"
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "nlp_annotations",
        "intent_confidence",
        existing_type=sa.NUMERIC(precision=5, scale=4),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "nlp_annotations",
        "sentiment",
        existing_type=postgresql.ENUM("positive", "neutral", "negative", name="sentiment_label"),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_nlp_annotations_message_id"), table_name="nlp_annotations")
    op.create_index(
        op.f("ix_nlp_annotations_buyer_message_id"),
        "nlp_annotations",
        ["buyer_message_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_nlp_annotations_seller_id"), "nlp_annotations", ["seller_id"], unique=False
    )
    op.drop_constraint(
        op.f("nlp_annotations_message_id_fkey"), "nlp_annotations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "nlp_annotations", "sellers", ["seller_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "nlp_annotations", "buyer_messages", ["buyer_message_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("nlp_annotations", "entities")
    op.drop_column("nlp_annotations", "sentiment_confidence")
    op.drop_column("nlp_annotations", "extracted_offer_price")
    op.drop_column("nlp_annotations", "model_version")
    op.drop_column("nlp_annotations", "message_id")
    op.drop_index(
        op.f("ix_platform_credentials_external_user_id"), table_name="platform_credentials"
    )
    op.drop_column("platform_credentials", "external_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "platform_credentials",
        sa.Column("external_user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_platform_credentials_external_user_id"),
        "platform_credentials",
        ["external_user_id"],
        unique=False,
    )
    op.add_column(
        "nlp_annotations", sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "nlp_annotations",
        sa.Column("model_version", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.add_column(
        "nlp_annotations",
        sa.Column(
            "extracted_offer_price",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "nlp_annotations",
        sa.Column(
            "sentiment_confidence",
            sa.NUMERIC(precision=5, scale=4),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "nlp_annotations",
        sa.Column(
            "entities", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "nlp_annotations", type_="foreignkey")
    op.drop_constraint(None, "nlp_annotations", type_="foreignkey")
    op.create_foreign_key(
        op.f("nlp_annotations_message_id_fkey"),
        "nlp_annotations",
        "buyer_messages",
        ["message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_nlp_annotations_seller_id"), table_name="nlp_annotations")
    op.drop_index(op.f("ix_nlp_annotations_buyer_message_id"), table_name="nlp_annotations")
    op.create_index(
        op.f("ix_nlp_annotations_message_id"), "nlp_annotations", ["message_id"], unique=True
    )
    op.alter_column(
        "nlp_annotations",
        "sentiment",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("positive", "neutral", "negative", name="sentiment_label"),
        existing_nullable=False,
    )
    op.alter_column(
        "nlp_annotations",
        "intent_confidence",
        existing_type=sa.Float(),
        type_=sa.NUMERIC(precision=5, scale=4),
        existing_nullable=False,
    )
    op.alter_column(
        "nlp_annotations",
        "intent",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM(
            "offer", "question", "status_check", "spam", "other", name="intent_label"
        ),
        existing_nullable=False,
    )
    op.drop_column("nlp_annotations", "raw_output")
    op.drop_column("nlp_annotations", "sentiment_score")
    op.drop_column("nlp_annotations", "seller_id")
    op.drop_column("nlp_annotations", "buyer_message_id")
    op.create_unique_constraint(
        op.f("uq_conversations_seller_buyer"),
        "conversations",
        ["seller_id", "buyer_handle"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(None, "buyer_messages", type_="foreignkey")
    op.drop_index(op.f("ix_buyer_messages_seller_id"), table_name="buyer_messages")
    op.drop_column("buyer_messages", "processed_at")
    op.drop_column("buyer_messages", "seller_id")
    op.drop_index(op.f("ix_sales_seller_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_negotiation_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_listing_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_item_id"), table_name="sales")
    op.drop_table("sales")
    op.drop_index(op.f("ix_offer_signals_seller_id"), table_name="offer_signals")
    op.drop_index(op.f("ix_offer_signals_buyer_message_id"), table_name="offer_signals")
    op.drop_table("offer_signals")
    op.drop_index(op.f("ix_entity_mentions_seller_id"), table_name="entity_mentions")
    op.drop_index(op.f("ix_entity_mentions_buyer_message_id"), table_name="entity_mentions")
    op.drop_table("entity_mentions")
    op.drop_index(op.f("ix_clarification_requests_seller_id"), table_name="clarification_requests")
    op.drop_index(
        op.f("ix_clarification_requests_conversation_id"), table_name="clarification_requests"
    )
    op.drop_index(
        op.f("ix_clarification_requests_buyer_message_id"), table_name="clarification_requests"
    )
    op.drop_table("clarification_requests")
    op.drop_index(op.f("ix_negotiations_seller_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_listing_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_conversation_id"), table_name="negotiations")
    op.drop_table("negotiations")
    # ### end Alembic commands ###
